on:
  issues:
    types: [opened]
    
env:
  GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    
    steps:
    - name: Run assignment to one project
      uses: srggrs/assign-one-project-github-action@1.1.0
      with:
        # Assigned Project
        project: 'https://github.com/brosela/cupcakes/projects/1'
